# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac788b6feeb0fa03953eb403f3ffaa645fe8733938bdb3a349ee7ea4fc97a3701cfdfa54237a7a5a356d4d58962fb85fe643e672a988f3ec01e03ddadef925f

test:
  secret_key_base: 1136b74a359b1b4721ade95d82b2962e4302df9e922b4fcf9436b904400e14e3aaa3b32eadf0c4754501cb27cf1b023b9f6763e61a8a6cd946f66fafe5885804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
